cf:
  apiHost: api.run.pcfone.io
  refreshToken: xxxxxx
  organizationBlackList:
    - system

token:
  provider: sso

logging:
  level:
    org.springframework: INFO
    org.cloudfoundry.reactor: DEBUG

# Set schedule for this task to adhere to
# @see https://crontab.guru for help, first parameter is seconds
cron:
  collection: "0 0 0 * * *"
  execution: "0 0 2 * * *"

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,logfile,prometheus
